/* 
  Sketch generated by the Arduino IoT Cloud Thing "Task 3.2C"
  https://create.arduino.cc/cloud/things/1ead336e-e60e-4b5b-9a55-ffc28921edbf 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String show;
  int lIGHT_FELT;
  bool sun_light;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <BH1750FVI.h>

BH1750FVI lightmeter(BH1750FVI::k_DevModeContLowRes);

WiFiClient client;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 
  pinMode(4,OUTPUT);
  lightmeter.begin();
  delay(2000);
  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  lIGHT_FELT = lightmeter.GetLightIntensity();
  delay(2000);
  
  if(lIGHT_FELT > 100) {
    sun_light = true;
    Serial.print("Efficient Light is present.");
    show = "The efficient light was present at this time for the plant.";
    digitalWrite(4,sun_light);
    delay(1000);
  }
  
  else {
    sun_light = false;
    Serial.print("Efficient Light is not present.");
    show = "The efficient light was not present at this time for the plant.";
    digitalWrite(4,sun_light);
  }
  delay(2000);
}
